In [22]:
class Vehicle:
    def __init__ (self,make, model, year):
        self.make = make
        self.model = model
        self.year = year

    def display_info(self):
        print (f"{self.make}, {self.model}, {self.year}")
    
    def __add__ (self,other):
        if isinstance(other,Vehicle):
            combined_make_model = f"{self.make}{self.model}+{other.make}{other.model}"
            return combined_make_model
        else:
            return NotImplemented
        
v1 = Vehicle("Hyundai","i20", 2020)
v2 = Vehicle("Maruti","WagonR", 2021)

v1.display_info()
v2.display_info()


Hyundai, i20, 2020
Maruti, WagonR, 2021


In [21]:
class Car(Vehicle):
    def __init__(self,make,model,year,num_doors,fuel_type):
        super().__init__(make, model, year)
        self.num_doors = num_doors
        self.fuel_type = fuel_type
    def display_info(self):
        super().display_info()
        print(f"Number Of Doors:{self.num_doors}, Fuel Type:{self.fuel_type}")
        
v1= Vehicle("Mahindra","Thar", 2020)
v2= Vehicle("Hyundai","Creta", 2021)

v1.display_info()
v2.display_info() 
result= v1 + v2
print ("\n Combined make and model: ")
print(result)

car1= Car("Hyundai", "Creta", 2024, 4, "Gasoline") 
car2= Car("Hyundai", "Verna", 2022, 4, "Diesel") 



print("\n Car1:\n")
car1.display_info()
print("\n Car2:\n")
car2.display_info()


Mahindra, Thar, 2020
Hyundai, Creta, 2021

 Combined make and model: 
MahindraThar+HyundaiCreta

 Car1:

Hyundai, Creta, 2024
Number Of Doors:4, Fuel Type:Gasoline

 Car2:

Hyundai, Verna, 2022
Number Of Doors:4, Fuel Type:Diesel


In [23]:
#q7
# Creating a list of numbers
numbers_list = [1, 2, 3, 4, 5]

# Displaying the original list
print("Original List:", numbers_list)

# Adding elements to the list
numbers_list.append(6)  # Appending a single element
numbers_list.extend([7, 8, 9])  # Extending with multiple elements

# Displaying the list after adding elements
print("List after adding elements:", numbers_list)

# Accessing elements by index
index_to_access = 2
element_at_index = numbers_list[index_to_access]
print(f"Element at index {index_to_access}: {element_at_index}")

# Modifying elements by index
index_to_modify = 1
new_value = 10
numbers_list[index_to_modify] = new_value
print(f"List after modifying element at index {index_to_modify}: {numbers_list}")

# Removing elements from the list
element_to_remove = 4
if element_to_remove in numbers_list:
    numbers_list.remove(element_to_remove)
    print(f"List after removing element {element_to_remove}: {numbers_list}")
else:
    print(f"Element {element_to_remove} not found in the list.")

# Removing element by index
index_to_remove = 3
if 0 <= index_to_remove < len(numbers_list):
    removed_element = numbers_list.pop(index_to_remove)
    print(f"List after removing element at index {index_to_remove}: {numbers_list}")
    print(f"Removed element: {removed_element}")
else:
    print(f"Index {index_to_remove} is out of bounds.")

# Displaying the final list
print("Final List:", numbers_list)

Original List: [1, 2, 3, 4, 5]
List after adding elements: [1, 2, 3, 4, 5, 6, 7, 8, 9]
Element at index 2: 3
List after modifying element at index 1: [1, 10, 3, 4, 5, 6, 7, 8, 9]
List after removing element 4: [1, 10, 3, 5, 6, 7, 8, 9]
List after removing element at index 3: [1, 10, 3, 6, 7, 8, 9]
Removed element: 5
Final List: [1, 10, 3, 6, 7, 8, 9]


In [26]:
#q8
# Creating a tuple
my_tuple = (1, 2, 3, 4, 5)

# Accessing elements by index
index_to_access = 2
element_at_index = my_tuple[index_to_access]
print(f"Element at index {index_to_access}: {element_at_index}")

# Trying to modify a tuple (Note: This will raise an error as tuples are immutable)
try:
    my_tuple[0] = 10
except TypeError as e:
    print(f"Error: {e}")

# Concatenating tuples
another_tuple = (6, 7, 8)
concatenated_tuple = my_tuple + another_tuple
print("Concatenated Tuple:", concatenated_tuple)

# Repeating a tuple
repeated_tuple = my_tuple * 2
print("Repeated Tuple:", repeated_tuple)

# Checking if an element is present in the tuple
element_to_check = 3
if element_to_check in my_tuple:
    print(f"{element_to_check} is present in the tuple.")
else:
    print(f"{element_to_check} is not present in the tuple.")

# Finding the length of the tuple
tuple_length = len(my_tuple)
print("Length of the Tuple:", tuple_length)

# Displaying the original tuple
print("Original Tuple:", my_tuple)



Element at index 2: 3
Error: 'tuple' object does not support item assignment
Concatenated Tuple: (1, 2, 3, 4, 5, 6, 7, 8)
Repeated Tuple: (1, 2, 3, 4, 5, 1, 2, 3, 4, 5)
3 is present in the tuple.
Length of the Tuple: 5
Original Tuple: (1, 2, 3, 4, 5)


In [27]:
#q9
# Creating sets
set1 = {1, 2, 3, 4, 5}
set2 = {3, 4, 5, 6, 7}

# Displaying the original sets
print("Set 1:", set1)
print("Set 2:", set2)

# Union of sets
union_set = set1.union(set2)
print("Union of Set 1 and Set 2:", union_set)

# Intersection of sets
intersection_set = set1.intersection(set2)
print("Intersection of Set 1 and Set 2:", intersection_set)

# Difference between sets
difference_set1_minus_set2 = set1.difference(set2)
difference_set2_minus_set1 = set2.difference(set1)

print("Difference (Set 1 - Set 2):", difference_set1_minus_set2)
print("Difference (Set 2 - Set 1):", difference_set2_minus_set1)

# Symmetric difference (elements present in either set, but not in both)
symmetric_difference_set = set1.symmetric_difference(set2)
print("Symmetric Difference of Set 1 and Set 2:", symmetric_difference_set)


Set 1: {1, 2, 3, 4, 5}
Set 2: {3, 4, 5, 6, 7}
Union of Set 1 and Set 2: {1, 2, 3, 4, 5, 6, 7}
Intersection of Set 1 and Set 2: {3, 4, 5}
Difference (Set 1 - Set 2): {1, 2}
Difference (Set 2 - Set 1): {6, 7}
Symmetric Difference of Set 1 and Set 2: {1, 2, 6, 7}


In [28]:
#q10
# Creating a dictionary
my_dict = {'name': 'John', 'age': 25, 'city': 'New York'}

# Displaying the original dictionary
print("Original Dictionary:", my_dict)

# Accessing values by key
name_value = my_dict['name']
print("Name:", name_value)

# Adding a new key-value pair
my_dict['occupation'] = 'Engineer'
print("Dictionary after adding a new key-value pair:", my_dict)

# Updating the value of an existing key
my_dict['age'] = 26
print("Dictionary after updating the value of 'age':", my_dict)

# Checking if a key is present in the dictionary
key_to_check = 'city'
if key_to_check in my_dict:
    print(f"{key_to_check} is present in the dictionary.")
else:
    print(f"{key_to_check} is not present in the dictionary.")

# Removing a key-value pair
key_to_remove = 'occupation'
if key_to_remove in my_dict:
    del my_dict[key_to_remove]
    print(f"Dictionary after removing the key-value pair with key '{key_to_remove}':", my_dict)
else:
    print(f"Key '{key_to_remove}' not found in the dictionary.")

# Displaying the final dictionary
print("Final Dictionary:", my_dict)


Original Dictionary: {'name': 'John', 'age': 25, 'city': 'New York'}
Name: John
Dictionary after adding a new key-value pair: {'name': 'John', 'age': 25, 'city': 'New York', 'occupation': 'Engineer'}
Dictionary after updating the value of 'age': {'name': 'John', 'age': 26, 'city': 'New York', 'occupation': 'Engineer'}
city is present in the dictionary.
Dictionary after removing the key-value pair with key 'occupation': {'name': 'John', 'age': 26, 'city': 'New York'}
Final Dictionary: {'name': 'John', 'age': 26, 'city': 'New York'}


In [29]:
#NUMPY

import numpy as np

arr1 = np.array([[1, 2],[3, 4]])
 
arr2 = np.array([[4, 3],[2, 1]])
print ("\nArray sum:\n", arr1 + arr2)
print ("\nArray Diff:\n", arr1 - arr2)
print ("\nArray Multi:\n", arr1 * arr2)
print ("\nArray Div:\n", arr1 / arr2)


Array sum:
 [[5 5]
 [5 5]]

Array Diff:
 [[-3 -1]
 [ 1  3]]

Array Multi:
 [[4 6]
 [6 4]]

Array Div:
 [[0.25       0.66666667]
 [1.5        4.        ]]


In [32]:
#index
print("index")
print(arr1[1:])
print(arr1[:2])
print(arr1[:])
print(arr1[1:4])

#slice
print("\n\nSlice")
print(arr2[1::2])
print(arr2[::2])

index
[[3 4]]
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[3 4]]


Slice
[[2 1]]
[[4 3]]


In [33]:
#mean median mode
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 3, 5, 4, 6, 4, 3])

# Calculate the mean
mean = np.mean(arr)

# Calculate the median
median = np.median(arr)

# Calculate the mode

mode = np.unique(arr)[np.argmax(np.bincount(arr))]

# Print the results
print("Mean:", mean)
print("Median:", median)
print("Mode:", mode)


Mean: 3.4444444444444446
Median: 3.0
Mode: 4


In [35]:
#reshape
import numpy as np

arr = np.array([(1,2,3,4,5),(10,9,8,7,6)])
print("Initial shape:",arr.shape)
print (arr)
arr=arr.reshape(5,2)
print("Shape after reshaping:",arr.shape)
print (arr)

print("\n\n")
#transpose
Trans_arr = arr.T
print("\nTranspose of Array: ")
print(Trans_arr)

Initial shape: (2, 5)
[[ 1  2  3  4  5]
 [10  9  8  7  6]]
Shape after reshaping: (5, 2)
[[ 1  2]
 [ 3  4]
 [ 5 10]
 [ 9  8]
 [ 7  6]]




Transpose of Array: 
[[ 1  3  5  9  7]
 [ 2  4 10  8  6]]
